
project := "foo2_project".

project_version := "1.0".

buildfile_version := "1.0".

build mybuild.

 options.

  on toolchain_select("-t", "--toolchain=tool", "Select toolchain, clang or gcc.").

 end options.

 get toolchain_select.

 if ( toolchain_select != "clang" && toolchain_select != "gcc" ).

   var toolchain_select := "gcc".

 end if.

 message("Building foo...").

 make filepath include_path from "resources" to "include".

 files MyAppSourceFiles("src.directory").

 sources MyAppSource(MyAppSourceFiles).

 compiler MyCompilerFlags("-Wall", "-I " + include_path).

 toolchain MyToolChain(toolchain_select,MyCompilerFlags).

 output foo2("dynamic_library",MyAppSource,MyToolChain).

end build.



