
project := "My Project".

project_version := "1.0".

buildfile_version := "1.0".

build mybuild.

 options.

  on toolchain_select("-t", "--toolchain=tool", "Select toolchain, clang or gcc.").

 end options.

 get toolchain_select.

 if ( toolchain_select != "clang" && toolchain_select != "gcc" ).

   var toolchain_select := "gcc".

 end if.

 message("Building foo...").

 files MyAppSourceFiles("src.directory").

 sources MyAppSource(MyAppSourceFiles).

 compiler MyCompilerFlags("-Wall").

 toolchain MyToolChain(toolchain_select,MyCompilerFlags).

 output MyApp("application",MyAppSource,MyToolChain).

 launch(MyApp).

end build.



